version: '3'

services:

  plexa-clinicaltrials-matcher:
    image: aehrc/clinicaltrials-matcher:0.1.1-2020CT
    ports:
      - 8080:80
    links:
      - plexa-elasticsearch
      - plexa-quickumls-rest

  plexa-elasticsearch:
    image: aehrc/clinicaltrials-elasticsearch:5.0.2-2020
    #command: elasticsearch -Enetwork.host=0.0.0.0 -Epath.repo=/usr/share/elasticsearch
    environment:
      - xpack.security.enabled=false
      - TZ=Australia/Brisbane
      - "ES_JAVA_OPTS=-Xms6g -Xmx6g"
    ports:
      - 9200:9200
      - 9300:9300

  plexa-quickumls-rest:
    image: aehrc/quickumls-rest:1.2.3-2018AA